CLASS ltcl_test DEFINITION DEFERRED.
CLASS ycl_model_status_api DEFINITION LOCAL FRIENDS ltcl_test.
CLASS ltcl_test DEFINITION FOR TESTING DURATION SHORT RISK LEVEL HARMLESS FINAL.
  PUBLIC SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS ltcl_test IMPLEMENTATION.

ENDCLASS.
