name: abap ci
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: https://npm.pkg.github.com/
      - name: Clean install of npm dependencies
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: lint abap files with abaplint
        run: npx abaplint
      - name: Downport abap to 702
        run: npm run abap-downport
      - name: Transpile abap to js
        run: npm run abap-transpile
      - name: Run abap unit tests
        run: npm run abap-unit-tests
